name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit"]

    steps:
      - uses: actions/checkout@main

      - uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - uses: leafo/gh-actions-luarocks@v4

      - name: Build
        run: luarocks make

      - name: Install bit32 where needed
        if: matrix.luaVersion == '5.1' || matrix.luaVersion == '5.3' || matrix.luaVersion == '5.4'
        run: luarocks install bit32

      - name: Test
        run: |
          luarocks test