name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit"]

    steps:
      - uses: actions/checkout@main

      - uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - uses: leafo/gh-actions-luarocks@v4

      - name: Build
        run: luarocks make

      - name: Test
        run: |
          luarocks install bit32
          luarocks install busted
          luarocks install penlight
          luarocks test